### PR TITLE
install-hab: Pin hab cli to 0.61.0-20180815171844

### PR DESCRIPTION
**Pull request by indradhanush**

### CODE REVIEW

**Comment by kosyfrances** [comment]
@indradhanush you'd need to rebase this branch.

**Comment by indradhanush** [comment]
@kosyfrances Hmm, but why? I don't see any conflicts with `master`. Sorry I don't follow.

**Comment by kosyfrances** [comment]
So that I can test your changes with the new things on master alongside, because I got stuck with this error because of outdated hab commands
```Switched to context "default".
+ vagrant ssh node-0 -- sudo hab sup start core/etcd --topology leader --channel stable
error: The subcommand 'start' wasn't recognized
	Did you mean 'stat'?

If you believe you received this message in error, try re-running with 'hab sup -- start'

USAGE:
    hab sup <SUBCOMMAND>

For more information try --help
+ popd
```

**Comment by indradhanush** [comment]
Merged on the command line.

**Pull request merged**
